apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: adevinta-micro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adevinta-micro
  template:
    metadata:
      labels:
        app: adevinta-micro
    spec:
      containers:
      - name: <your-container-name>
        image: <your-image-url>
        ports:
        - containerPort: 80
        env:
        - name: IS_EKS
          value: "True"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
