tokenizer:
  pretrained_model_name_or_path: "distilbert-base-uncased-finetuned-sst-2-english"
  cache_dir: null
  force_download: False
  local_files_only: False
  revision: "main"
model:
  pretrained_model_name_or_path: "distilbert-base-uncased-finetuned-sst-2-english"
  config: null
  cache_dir: null
  ignore_mismatched_sizes: False
  force_download: False
  local_files_only: False
  revision: "main"
  use_safetensors: null
  weights_only: True
